export const PRODUCTS = [
	{
		category: 1,
		items: [
			{
				title: 'Удлинители в бухте',
				description: `Удлинители с медным кабелем «ПВС», без заземления,
       <br/>
       со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители с медным кабелем «ПВС»<br/>
       без заземления, <br/> со степенью защиты «IP44» <br/> (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», <br/> с поддержанием напряжения сети в «220В»`,
				grounding: false,
				isProfessional: false,
				category: 1,
				socket: 'крышка на розетке',
				copper: '100% медь',
				variants: [
					{
						variant: 2200,
						options: [
							{
								article: 101,
								plugs: '2х1,0',
								length: '10 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 102,
								plugs: '2х1,0',
								length: '20 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 103,
								plugs: '2х1,0',
								length: '30 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 104,
								plugs: '2х1,0',
								length: '40 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 105,
								plugs: '2х1,0',
								length: '50 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
						],
					},
					{
						variant: 3500,
						options: [
							{
								article: 106,
								plugs: '2х1,5',
								length: '10 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 107,
								plugs: '2х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 108,
								plugs: '2х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 109,
								plugs: '2х1,5',
								length: '40 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 110,
								plugs: '2х1,5',
								length: '50 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 111,
								plugs: '2х2,5',
								length: '10 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 112,
								plugs: '2х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 113,
								plugs: '2х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 114,
								plugs: '2х2,5',
								length: '40 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 115,
								plugs: '2х2,5',
								length: '50 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
						],
					},
				],
				images: {
					main: `/product/pvc/1/main.png`,
					gallery: [
						{
							1: '/product/pvc/1/1.png',
							2: '/product/pvc/1/2.png',
							3: '/product/pvc/1/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители в бухте',
				description: `Удлинители с медным кабелем «ПВС», с заземлением,
       <br/>
       со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители с медным кабелем «ПВС», <br/> с заземлением,
       <br/>
       со степенью защиты «IP44»<br/> (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А»,<br/> с поддержанием напряжения сети в «220В»`,
				grounding: true,
				isProfessional: false,
				category: 1,
				copper: '100% медь',
				socket: 'крышка в розетке',
				variants: [
					{
						variant: 2200,
						options: [
							{
								article: 116,
								plugs: '3х1,0',
								length: '10 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 117,
								plugs: '3х1,0',
								length: '20 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 118,
								plugs: '3х1,0',
								length: '30 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 119,
								plugs: '3х1,0',
								length: '40 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 120,
								plugs: '3х1,0',
								length: '50 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
					{
						variant: 3500,
						options: [
							{
								article: 121,
								plugs: '3х1,5',
								length: '10 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 122,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 123,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 124,
								plugs: '3х1,5',
								length: '40 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 125,
								plugs: '3х1,5',
								length: '50 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 126,
								plugs: '3х2,5',
								length: '10 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 127,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 128,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 129,
								plugs: '3х2,5',
								length: '40 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 130,
								plugs: '3х2,5',
								length: '50 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/pvc/1/main.png`,
					gallery: [
						{
							1: '/product/pvc/1/1.png',
							2: '/product/pvc/1/2.png',
							3: '/product/pvc/1/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители на пластиковой рамке',
				description: `Удлинители с медным кабелем «ПВС» на пластиковой рамке, 
       <br/>
       без заземления, со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
				mobiledescrip: `Удлинители с медным кабелем «ПВС»<br/> на пластиковой рамке, 
       <br/>
       без заземления, со степенью защиты «IP44»<br/> (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А»,<br/> с поддержанием напряжения сети в «220В»`,
				grounding: false,
				isProfessional: false,
				copper: '100% медь',
				category: 1,
				socket: 'крышка на розетке',
				variants: [
					{
						variant: 2200,
						options: [
							{
								article: 201,
								plugs: '2х1,0',
								length: '10 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 202,
								plugs: '2х1,0',
								length: '20 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 203,
								plugs: '2х1,0',
								length: '30 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 204,
								plugs: '2х1,0',
								length: '40 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
						],
					},
					{
						variant: 3500,
						options: [
							{
								article: 205,
								plugs: '2х1,5',
								length: '10 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 206,
								plugs: '2х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 207,
								plugs: '2х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 208,
								plugs: '2х2,5',
								length: '10 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 209,
								plugs: '2х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 210,
								plugs: '2х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
						],
					},
				],
				images: {
					main: `/product/pvc/3/main.png`,
					gallery: [
						{
							1: '/product/pvc/3/1.png',
							2: '/product/pvc/3/2.png',
							3: '/product/pvc/3/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители на пластиковой рамке',
				description: `Удлинители с медным кабелем «ПВС» на пластиковой рамке,
       <br/>
       с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
				mobiledescrip: `Удлинители с медным кабелем «ПВС»<br/> на пластиковой рамке,
       <br/>
       с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А» <br/> с поддержанием напряжения сети в «220В»`,
				grounding: true,
				isProfessional: false,
				copper: '100% медь',
				category: 1,
				socket: 'крышка в розетке',
				variants: [
					{
						variant: 2200,
						options: [
							{
								article: 211,
								plugs: '3х1,0',
								length: '10 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 212,
								plugs: '3х1,0',
								length: '20 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 213,
								plugs: '3х1,0',
								length: '30 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 214,
								plugs: '3х1,0',
								length: '40 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
					{
						variant: 3500,
						options: [
							{
								article: 215,
								plugs: '3х1,5',
								length: '10 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 216,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 217,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 218,
								plugs: '3х2,5',
								length: '10 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 219,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 220,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/pvc/3/main.png`,
					gallery: [
						{
							1: '/product/pvc/3/1.png',
							2: '/product/pvc/3/2.png',
							3: '/product/pvc/3/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители на садовой катушке',
				description: `Удлинители с медным кабелем «ПВС», без заземления,
       <br/>
       на садовой катушке для комфортного наматывания и хранения,
       <br/>
       со степенью защиты «IP44» (каучуковая крышка на розетке),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
				mobiledescrip: `Удлинители с медным кабелем «ПВС»,<br/> без заземления,
       на садовой катушке <br/> для комфортного наматывания и хранения,
       <br/>
       со степенью защиты «IP44» <br/> (каучуковая крышка на розетке),
       <br/>
       с европейской вилкой «16А» <br/> с поддержанием напряжения сети в «220В»`,
				grounding: false,
				isProfessional: true,
				copper: '100% медь',
				category: 1,
				socket: 'крышка на розетке',
				variants: [
					{
						variant: 2200,
						options: [
							{
								article: 301,
								plugs: '2х1,0',
								length: '20 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 302,
								plugs: '2х1,0',
								length: '30 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 303,
								plugs: '2х1,0',
								length: '40 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 304,
								plugs: '2х1,0',
								length: '50 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: false,
							},
						],
					},
					{
						variant: 3500,
						options: [
							{
								article: 305,
								plugs: '2х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 306,
								plugs: '2х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 307,
								plugs: '2х1,5',
								length: '40 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 308,
								plugs: '2х1,5',
								length: '50 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: false,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 309,
								plugs: '2х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 310,
								plugs: '2х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 311,
								plugs: '2х2,5',
								length: '40 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
							{
								article: 312,
								plugs: '2х2,5',
								length: '50 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: false,
							},
						],
					},
				],
				images: {
					main: `/product/pvc/5/main.png`,
					gallery: [
						{
							1: '/product/pvc/5/1.png',
							2: '/product/pvc/5/2.png',
							3: '/product/pvc/5/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители на садовой катушке',
				description: `Удлинители с медным кабелем «ПВС», с заземлением,
       <br/>
       на садовой катушке для комфортного наматывания и хранения,
       <br/>
       со степенью защиты «IP44» (каучуковая крышка на розетке),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители с медным кабелем «ПВС», <br/> с заземлением,
       на садовой катушке <br/> для комфортного наматывания и хранения,
       <br/>
       со степенью защиты «IP44» <br/> (каучуковая крышка на розетке),
       <br/>
       с европейской вилкой «16А» <br/> с поддержанием напряжения сети «220В»`,
				grounding: true,
				isProfessional: true,
				category: 1,
				copper: '100% медь',
				socket: 'крышка на розетке',
				variants: [
					{
						variant: 2200,
						options: [
							{
								article: 313,
								plugs: '3х1,0',
								length: '20 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 314,
								plugs: '3х1,0',
								length: '30 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 315,
								plugs: '3х1,0',
								length: '40 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 316,
								plugs: '3х1,0',
								length: '50 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
					{
						variant: 3500,
						options: [
							{
								article: 317,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 318,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 319,
								plugs: '3х1,5',
								length: '40 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 320,
								plugs: '3х1,5',
								length: '50 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 321,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 322,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 323,
								plugs: '3х2,5',
								length: '40 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 324,
								plugs: '3х2,5',
								length: '50 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/pvc/5/main.png`,
					gallery: [
						{
							1: '/product/pvc/5/1.png',
							2: '/product/pvc/5/2.png',
							3: '/product/pvc/5/3.png',
						},
					],
				},
			},

			{
				title: 'Удлинители на пластиковой катушке',
				description: `Удлинители с медным кабелем «ПВС», без заземления,
       <br/>
       на пластиковой катушке для легкого наматывания и хранения,
       <br/>
       со степенью защиты «IP20» (стандартная защита),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители с медным кабелем «ПВС», <br/> без заземления,
       на пластиковой катушке <br/> для легкого наматывания и хранения,
       <br/>
       со степенью защиты «IP20» <br/> (стандартная защита),
       <br/>
       с европейской вилкой «16А» <br/> с поддержанием напряжения сети «220В»`,
				grounding: false,
				isProfessional: true,
				copper: '100% медь',
				category: 1,
				socket: 'твердая защита',
				variants: [
					{
						variant: 2200,
						options: [
							{
								article: 401,
								plugs: '2х1,0',
								length: '20 м',
								security: 'IP20',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: false,
							},
							{
								article: 402,
								plugs: '2х1,0',
								length: '30 м',
								security: 'IP20',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: false,
							},
							{
								article: 403,
								plugs: '2х1,0',
								length: '40 м',
								security: 'IP20',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: false,
							},
							{
								article: 404,
								plugs: '2х1,0',
								length: '50 м',
								security: 'IP20',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: false,
							},
						],
					},
					{
						variant: 3500,
						options: [
							{
								article: 405,
								plugs: '2х1,5',
								length: '20 м',
								security: 'IP20',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: false,
							},
							{
								article: 406,
								plugs: '2х1,5',
								length: '30 м',
								security: 'IP20',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: false,
							},
							{
								article: 407,
								plugs: '2х1,5',
								length: '40 м',
								security: 'IP20',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: false,
							},
							{
								article: 408,
								plugs: '2х1,5',
								length: '50 м',
								security: 'IP20',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: false,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 409,
								plugs: '2х2,5',
								length: '20 м',
								security: 'IP20',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: false,
							},
							{
								article: 410,
								plugs: '2х2,5',
								length: '30 м',
								security: 'IP20',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: false,
							},
							{
								article: 411,
								plugs: '2х2,5',
								length: '40 м',
								security: 'IP20',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: false,
							},
							{
								article: 412,
								plugs: '2х2,5',
								length: '50 м',
								security: 'IP20',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: false,
							},
						],
					},
				],
				images: {
					main: `/product/pvc/4/main.png`,
					gallery: [
						{
							1: '/product/pvc/4/1.png',
							2: '/product/pvc/4/2.png',
							3: '/product/pvc/4/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители на пластиковой катушке',
				description: `Удлинители с медным кабелем «ПВС», с заземлением,
       <br/>
       на пластиковой катушке для легкого наматывания и хранения,
       <br/>
       со степенью защиты «IP20» (стандартная защита),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители с медным кабелем «ПВС»,<br/> с заземлением,
       на пластиковой катушке <br/> для легкого наматывания и хранения,
       <br/>
       со степенью защиты «IP20» <br/> (стандартная защита),
       <br/>
       с европейской вилкой «16А» <br/> с поддержанием напряжения сети в «220В»`,
				grounding: true,
				isProfessional: true,
				category: 1,
				socket: 'защита от мусора',
				copper: '100% медь',
				variants: [
					{
						variant: 2200,
						options: [
							{
								article: 413,
								plugs: '3х1,0',
								length: '20 м',
								security: 'IP20',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 414,
								plugs: '3х1,0',
								length: '30 м',
								security: 'IP20',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 415,
								plugs: '3х1,0',
								length: '40 м',
								security: 'IP20',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 416,
								plugs: '3х1,0',
								length: '50 м',
								security: 'IP20',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
					{
						variant: 3500,
						options: [
							{
								article: 417,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP20',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 418,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP20',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 419,
								plugs: '3х1,5',
								length: '40 м',
								security: 'IP20',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 420,
								plugs: '3х1,5',
								length: '50 м',
								security: 'IP20',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 421,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP20',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 422,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP20',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 423,
								plugs: '3х2,5',
								length: '40 м',
								security: 'IP20',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 424,
								plugs: '3х2,5',
								length: '50 м',
								security: 'IP20',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/pvc/6/main.png`,
					gallery: [
						{
							1: '/product/pvc/6/1.png',
							2: '/product/pvc/6/2.png',
							3: '/product/pvc/6/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители на пластиковой катушке',
				description: `Удлинители с медным кабелем «ПВС», с заземлением,
       <br/>
       на пластиковой катушке для легкого наматывания и хранения,
       <br/>
       со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители с медным кабелем «ПВС», <br/> с заземлением,
   
       на пластиковой катушке <br/> для легкого наматывания и хранения,
       <br/>
       со степенью защиты «IP44» <br/> (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А» <br/> с поддержанием напряжения сети «220В»`,
				grounding: true,
				isProfessional: true,
				category: 1,
				socket: 'крышка на розетке',
				copper: '100% медь',
				variants: [
					{
						variant: 2200,
						options: [
							{
								article: 425,
								plugs: '3х1,0',
								length: '20 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 426,
								plugs: '3х1,0',
								length: '30 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 427,
								plugs: '3х1,0',
								length: '40 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 428,
								plugs: '3х1,0',
								length: '50 м',
								security: 'IP44',
								power: '2200 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
					{
						variant: 3500,
						options: [
							{
								article: 429,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 430,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 431,
								plugs: '3х1,5',
								length: '40 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 432,
								plugs: '3х1,5',
								length: '50 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 433,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 434,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 435,
								plugs: '3х2,5',
								length: '40 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 436,
								plugs: '3х2,5',
								length: '50 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/pvc/7/main.png`,
					gallery: [
						{
							1: '/product/pvc/7/1.png',
							2: '/product/pvc/7/2.png',
							3: '/product/pvc/7/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители на металлической катушке',
				description: `Удлинители с медным кабелем «ПВС», с заземлением,
       <br/>
       на металлической катушке для легкого наматывания и хранения,
       <br/>
       со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители с медным кабелем «ПВС»,
       <br/> с заземлением,
       на металлической катушке <br/> для легкого наматывания и хранения,
       <br/>
       со степенью защиты «IP44» <br/> (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А» <br/> с поддержанием напряжения сети «220В»`,
				grounding: true,
				isProfessional: true,
				category: 1,
				socket: 'крышка на розетке',
				copper: '100% медь',
				variants: [
					{
						variant: 3500,
						options: [
							{
								article: 437,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 438,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 439,
								plugs: '3х1,5',
								length: '40 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 440,
								plugs: '3х1,5',
								length: '50 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 441,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 442,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 443,
								plugs: '3х2,5',
								length: '40 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 444,
								plugs: '3х2,5',
								length: '50 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/pvc/10/main.png`,
					gallery: [
						{
							1: '/product/pvc/10/1.png',
							2: '/product/pvc/10/2.png',
							3: '/product/pvc/10/3.png',
						},
					],
				},
			},
		],
	},
	{
		category: 2,
		items: [
			{
				title: 'Удлинители силовые в бухте',
				description: `Удлинители силовые с медным кабелем «КГТП ХЛ», с заземлением,
       <br/>
       со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители силовые с медным кабелем  <br/> «КГТП ХЛ», с заземлением,
       <br/>
       со степенью защиты «IP44» <br/> (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А»,<br/> с поддержанием напряжения сети «220В»`,
				grounding: true,
				isProfessional: false,
				isSpec: false,
				options: {
					isEco: false,
					isGost: false,
				},
				temp: 'от +40°C до -60°C ',
				copper: '100% медь',

				category: 2,

				variants: [
					{
						variant: 3500,
						options: [
							{
								article: 501,
								plugs: '3х1,5',
								length: '10 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 502,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 503,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 504,
								plugs: '3х1,5',
								length: '40 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 505,
								plugs: '3х1,5',
								length: '50 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 506,
								plugs: '3х2,5',
								length: '10 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 507,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 508,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 509,
								plugs: '3х2,5',
								length: '40 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 510,
								plugs: '3х2,5',
								length: '50 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/ukg/1/main.png`,
					gallery: [
						{
							1: '/product/ukg/1/1.png',
							2: '/product/ukg/1/2.png',
							3: '/product/ukg/1/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители силовые на колодке',
				description: `Удлинители силовые с медным кабелем «КГТП ХЛ», с заземлением,
       <br/>
       со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители силовые с медным кабелем <br/> «КГТП ХЛ», с заземлением,
       <br/>
       со степенью защиты «IP44» <br/> (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А»,<br/> с поддержанием напряжения сети «220В»`,
				grounding: true,
				isProfessional: false,
				isSpec: false,
				temp: 'от +40°C до -60°C ',
				copper: '100% медь',

				options: {
					isEco: false,
					isGost: false,
				},
				category: 2,

				variants: [
					{
						variant: 3500,
						options: [
							{
								article: 511,
								plugs: '3х1,5',
								length: '10 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '3 розетки',
								grounding: true,
							},
							{
								article: 512,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '3 розетки',
								grounding: true,
							},
							{
								article: 513,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '3 розетки',
								grounding: true,
							},
							{
								article: 514,
								plugs: '3х1,5',
								length: '40 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '3 розетки',
								grounding: true,
							},
							{
								article: 515,
								plugs: '3х1,5',
								length: '50 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '3 розетки',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 516,
								plugs: '3х2,5',
								length: '10 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '3 розетки',
								grounding: true,
							},
							{
								article: 517,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '3 розетки',
								grounding: true,
							},
							{
								article: 518,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '3 розетки',
								grounding: true,
							},
							{
								article: 519,
								plugs: '3х2,5',
								length: '40 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '3 розетки',
								grounding: true,
							},
							{
								article: 520,
								plugs: '3х2,5',
								length: '50 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '3 розетки',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/ukg/2/main.png`,
					gallery: [
						{
							1: '/product/ukg/2/1.png',
							2: '/product/ukg/2/2.png',
							3: '/product/ukg/2/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители силовые на колодке',
				description: `Удлинители силовые с медным кабелем «КГТП ХЛ», с заземлением,
       <br/>
       со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители силовые с медным кабелем <br/> «КГТП ХЛ», с заземлением,
       <br/>
       со степенью защиты «IP44» <br/> (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А»,<br/> с поддержанием напряжения сети «220В»`,
				grounding: true,
				isProfessional: false,
				isSpec: false,
				temp: 'от +40°C до -60°C ',
				copper: '100% медь',
				options: {
					isEco: false,
					isGost: false,
				},
				category: 2,

				variants: [
					{
						variant: 3500,
						options: [
							{
								article: 521,
								plugs: '3х1,5',
								length: '10 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 522,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 523,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 524,
								plugs: '3х1,5',
								length: '40 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 525,
								plugs: '3х1,5',
								length: '50 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 526,
								plugs: '3х2,5',
								length: '10 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 527,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 528,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 529,
								plugs: '3х2,5',
								length: '40 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 530,
								plugs: '3х2,5',
								length: '50 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/ukg/3/main.png`,
					gallery: [
						{
							1: '/product/ukg/3/1.png',
							2: '/product/ukg/3/2.png',
							3: '/product/ukg/3/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители силовые на пластиковой рамке',
				description: `Удлинители силовые с медным кабелем «КГТП ХЛ», с заземлением,
       <br/>
       на пластиковой рамке для легкого наматывания и хранения,
       <br/>
       со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители силовые с медным кабелем <br/> «КГТП ХЛ», с заземлением,
       на пластиковой <br/> рамке для легкого наматывания <br/> и хранения,
   
       со степенью защиты «IP44» <br/> (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А» <br/> с поддержанием напряжения сети «220В»`,
				grounding: true,
				isProfessional: true,
				temp: 'от +40°C до -60°C ',
				copper: '100% медь',
				isSpec: false,
				options: {
					isEco: true,
					isGost: false,
				},
				category: 2,

				variants: [
					{
						variant: 3500,
						options: [
							{
								article: 531,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 532,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 533,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
							{
								article: 534,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '1 розетка',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/ukg/4/main.png`,
					gallery: [
						{
							1: '/product/ukg/4/1.png',
							2: '/product/ukg/4/2.png',
							3: '/product/ukg/4/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители силовые на пластиковой катушке',
				fulltitle: 'Удлинители силовые на пластиковой катушке',
				description: `Удлинители силовые с медным кабелем «КГТП ХЛ», с заземлением,
       <br/>
       на пластиковой катушке для легкого наматывания и хранения,
       <br/>
       со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители силовые с медным кабелем <br/> «КГТП ХЛ», с заземлением,
       на пластиковой <br/> катушке для легкого наматывания <br/> и хранения,
       со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А» <br/> с поддержанием напряжения сети «220В»`,
				grounding: true,
				isProfessional: true,
				isSpec: false,
				isPlastic: true,
				isMetalic: false,
				temp: 'от +40°C до -60°C ',
				copper: '100% медь',
				options: {
					isEco: false,
					isGost: false,
				},
				category: 2,

				variants: [
					{
						variant: 3500,
						options: [
							{
								article: 535,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 536,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 537,
								plugs: '3х1,5',
								length: '40 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 538,
								plugs: '3х1,5',
								length: '50 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 539,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 540,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 541,
								plugs: '3х2,5',
								length: '40 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 542,
								plugs: '3х2,5',
								length: '50 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/ukg/5/main.png`,
					gallery: [
						{
							1: '/product/ukg/5/1.png',
							2: '/product/ukg/5/2.png',
							3: '/product/ukg/5/3.png',
						},
					],
				},
			},
			{
				title: 'Удлинители силовые на металлической катушке',
				fulltitle: 'Удлинители силовые на металлической катушке',
				description: `Удлинители силовые с медным кабелем «КГТП ХЛ», с заземлением,
       <br/>
       на металлической катушке для легкого наматывания и хранения,
       <br/>
       со степенью защиты «IP44» (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А», с поддержанием напряжения сети «220В»`,
				mobiledescrip: `Удлинители силовые с медным кабелем <br/> «КГТП ХЛ», с заземлением,
       на металлической <br/> катушке для легкого наматывания <br/> и хранения,
       со степенью защиты «IP44» <br/> (каучуковая розетка и крышка),
       <br/>
       с европейской вилкой «16А» <br/> с поддержанием напряжения сети «220В»`,
				grounding: true,
				isProfessional: true,
				isSpec: false,
				isPlastic: false,
				isMetalic: true,
				isCatushka: true,
				temp: 'от +40°C до -60°C ',
				copper: '100% медь',
				options: {},
				category: 2,

				variants: [
					{
						variant: 3500,
						options: [
							{
								article: 543,
								plugs: '3х1,5',
								length: '20 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 544,
								plugs: '3х1,5',
								length: '30 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 545,
								plugs: '3х1,5',
								length: '40 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 546,
								plugs: '3х1,5',
								length: '50 м',
								security: 'IP44',
								power: '3500 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
					{
						variant: 4000,
						options: [
							{
								article: 547,
								plugs: '3х2,5',
								length: '20 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 548,
								plugs: '3х2,5',
								length: '30 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 549,
								plugs: '3х2,5',
								length: '40 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
							{
								article: 550,
								plugs: '3х2,5',
								length: '50 м',
								security: 'IP44',
								power: '4000 Вт',
								socket: '4 розетки',
								grounding: true,
							},
						],
					},
				],
				images: {
					main: `/product/ukg/6/main.png`,
					gallery: [
						{
							1: '/product/ukg/6/1.png',
							2: '/product/ukg/6/2.png',
							3: '/product/ukg/6/3.png',
						},
					],
				},
			},
		],
	},
];
