name: Build Docker Image

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-builder:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Docker login to GitHub Container Registry
              run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Build and push base image for builder
              run: |
                  docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ghcr.io/${{ github.repository_owner }}/test:latest --target builder -t ghcr.io/${{ github.repository_owner }}/test:latest --build-arg NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }} .
                  docker push ghcr.io/${{ github.repository_owner }}/test:latest
