name: Notify on Telegram

on:
    workflow_run:
        workflows: ['Deploy Application']
        types:
            - completed

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Notify via Telegram
              run: |
                  curl -s -X POST \
                    https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
                    -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                    -d text="Pipeline finished on branch ${{ github.ref_name }}. Status: ${{ job.status }}"
